name: Fetch Bitcoin News

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data/scripts
    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - run: npm install

      # 4️⃣ Run fetch_news.mjs
      - run: node fetch_news.mjs

      # 5️⃣ Commit and push generated index.html
      - name: Commit and push generated index.html
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ../../index.html
          git commit -m "chore: update index.html" || echo "No changes to commit"
          git push
